(package "treemacs-nerd-icons"
         "0.0.1"
         "Emacs Nerd Font Icons theme for treemacs")

(website-url "https://github.com/rainstormstudio/treemacs-nerd-icons")
(keywords "file" "icons" "treemacs")

(package-file "treemacs-nerd-icons.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "nerd-icons")
(depends-on "treemacs")
